"""Application examples and manual tests for PyLage UI."""

from . import (
    accordion_manual,
    audio_video_canvas_manual,
    avatar_badge_divider_manual,
    button_manual,
    card_manual,
    carousel_manual,
    column_manual,
    data_feedback_manual,
    datepicker_manual,
    dialog_manual,
    drawer_manual,
    ui_kit_form_manual,
    grid_manual,
    heading_manual,
    input_manual,
    layout_primitives_manual,
    media_manual,
    menu_breadcrumbs_pagination_manual,
    modern_button_manual,
    nav_interaction_manual,
    pagination_manual,
    patterns_manual,
    popover_tooltip_manual,
    row_manual,
    select_manual,
    slider_radio_checkbox_manual,
    switch_manual,
    table_manual,
    tabs_manual,
    templates_manual,
    text_manual,
    themes_tokens_manual,
    manual_overview,
)
